"""empty message

Revision ID: ebdb61090534
Revises: 
Create Date: 2024-02-11 03:59:07.009156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdb61090534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('immediate_issues', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('immediate_issue_fixes', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('longterm_issues', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('longterm_issue_fixes', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('longterm_issue_fixes')
        batch_op.drop_column('longterm_issues')
        batch_op.drop_column('immediate_issue_fixes')
        batch_op.drop_column('immediate_issues')

    # ### end Alembic commands ###
